// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnnlvwormyauncederpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNubmx2d29ybXlhdW5jZWRlcnBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTc1NDQsImV4cCI6MjA2MDc5MzU0NH0.f3Rvc1BrdSjSOqKRcC8nQaQURldsTuDEErvycn0aIss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);